### ISSUE TITLE
Instructions for compiling FFI example are broken

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2219]
I'm going to wait for the README to be updated (https://github.com/dart-lang/samples/issues/29) before updating dart.dev.

**Comment by kwalrath** [comment]
@johnpryan how do you deal with signing? Here's what I see:

```
$ cd hello_library
$ cmake .
...seemingly successful output...
$ make
...seemingly successful output...
$ cd ..
$ dart hello.dart
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (dlopen(./hello_library/libhello.dylib, 1): no suitable image found.  Did find:
	./hello_library/libhello.dylib: code signature in (./hello_library/libhello.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      main (file:///Users/kathyw/tmp/ffi/hello_world/hello.dart:18:36)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by johnpryan** [comment]
https://github.com/dart-lang/sdk/issues/38314 is the issue to follow, but I think unsigning the dart binary will allow it to use unsigned libraries:

```
codesign --remove-signature <path to dart binary>
```
