### ISSUE TITLE
Crash report (Dart version=2.8.4 (stable))

### ISSUE THREAD

**Issue by rustkas** [dart-lang/site-www#2528]
I would like to share code example with crash report. I hope it help to do Dart VM better.

Code example:

```
import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

List<Isolate> isolates;

void main() async {
  await start();
  print('Press enter to exit');
  await stdin.first;
  stop();
  await stderr.flush();
  await stdout.flush();
  exit(0);
}

void start() async {
  isolates = [];
  isolates.add(await Isolate.spawn(runSomething, 'first'));
  isolates.add(await Isolate.spawn(runSomething, 'second'));
  isolates.add(await Isolate.spawn(runSomething, 'third'));
  // await stdout.flush();
  // await stderr.flush();
}

void runSomething(String arg) async {
  print('arg: $arg');

  var request =
      await HttpClient().getUrl(Uri.parse('https://swapi.co/api/people/1'));

  var response = await request.close();
  await stdin.first;
  await for (var contents in response.transform(Utf8Decoder())) {
    print(contents);
   
  }
}

void stop() {
  for (var i in isolates) {
    if (i != null) {
      i.kill(priority: Isolate.immediate);
      i = null;
      print('Killed');
    }
  }
}

```

Crash report:

```
ex_01_spawn_string>dart bin/main.dart
arg: first
arg: second
Press enter to exit
arg: third

===== CRASH =====
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=000000013FF074F0
Unhandled exception:
Bad state: No element
#0      Stream.first.<anonymous closure> (dart:async/stream.dart:1261:13)
#1      _RootZone.runGuarded (dart:async/zone.dart:1362:10)
#2      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#3      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
#4      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
#5      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:787:19)
#6      _StreamController._closeUnchecked (dart:async/stream_controller.dart:644:7)
#7      _StreamController.close (dart:async/stream_controller.dart:637:5)
#8      _Socket._onData (dart:io-patch/socket_patch.dart:1989:21)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#13     _StreamController._add (dart:async/stream_controller.dart:655:7)
#14     _StreamController.add (dart:async/stream_controller.dart:597:5)
#15     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1534:35)
#16     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1012:18)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
version=2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "windows_x64"
pid=163276, thread=161840, isolate=(null)(0000000000000000)
isolate_instructions=0, vm_instructions=13fba1010
Stack dump aborted because InitialRegisterCheck failed.
Unhandled exception:
FileSystemException: Error retrieving socket type, path = '' (OS Error: ╨Э╨╡╨▓╨╡╤А
╨╜╤Л╨╣ ╨┤╨╡╤Б╨║╤А╨╕╨┐╤В╨╛╤А.
, errno = 6)
#0      _StdIOUtils._nativeSocketType (dart:io-patch/stdio_patch.dart:48:7)
#1      new _RawSocket._readPipe (dart:io-patch/socket_patch.dart:1558:36)
#2      new _Socket._readPipe (dart:io-patch/socket_patch.dart:1839:28)
#3      _StdIOUtils._getStdioInputStream (dart:io-patch/stdio_patch.dart:23:32)
#4      stdin (dart:io/stdio.dart:410:26)
#5      runSomething (file:///E:/Users/tol_pc/Desktop/dart/%23src_projects/woolha/dart-spawn-kill-send-message-to-isolate/ex_01_spawn_string/bin/main.dart:33:9)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Unhandled exception:
FileSystemException: Error retrieving socket type, path = '' (OS Error: ╨Э╨╡╨▓╨╡╤А
╨╜╤Л╨╣ ╨┤╨╡╤Б╨║╤А╨╕╨┐╤В╨╛╤А.
, errno = 6)
#0      _StdIOUtils._nativeSocketType (dart:io-patch/stdio_patch.dart:48:7)
#1      new _RawSocket._readPipe (dart:io-patch/socket_patch.dart:1558:36)
#2      new _Socket._readPipe (dart:io-patch/socket_patch.dart:1839:28)
#3      _StdIOUtils._getStdioInputStream (dart:io-patch/stdio_patch.dart:23:32)
#4      stdin (dart:io/stdio.dart:410:26)
#5      runSomething (file:///E:/Users/tol_pc/Desktop/dart/%23src_projects/woolha/dart-spawn-kill-send-message-to-isolate/ex_01_spawn_string/bin/main.dart:33:9)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

**Comment by rustkas** [comment]
It is not right place for this issue. I report it to dart sdk project
