### ISSUE TITLE
`./dash_site serve` error

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5732]
### Describe the problem

I'm not sure how to interpret this. I'm pretty sure it's not my local edits, as I've just been writing plain text in a single markdown file...

Ran `dart pub get` and `pnpm install` and then tried again but it didn't change anything.

```
Building package executable... 
Built dart_site:dart_site.
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering liquid template ./src/content/language/macros.md (via TemplateContentRenderError)
[11ty] 2. Cannot read properties of null (reading 'length') (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of null (reading 'length')
[11ty]     at markdown.renderer.rules.fence (file:///Users/mbelanger/Projects/dart.dev/dart-3/src/_11ty/plugins/highlight.js:49:37)
[11ty]     at Renderer.render (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/markdown-it@14.1.0/node_modules/markdown-it/lib/renderer.mjs:313:28)
[11ty]     at MarkdownIt.render (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/markdown-it@14.1.0/node_modules/markdown-it/lib/index.mjs:530:24)
[11ty]     at file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/Engines/Markdown.js:79:33
[11ty]     at async Template._render (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/TemplateContent.js:532:19)
[11ty]     at async Template.renderPageEntryWithoutLayout (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/Template.js:432:25)
[11ty]     at async TemplateMap.populateContentDataInMap (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/TemplateMap.js:545:7)
[11ty]     at async TemplateMap.cache (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/TemplateMap.js:473:3)
[11ty]     at async TemplateWriter._createTemplateMap (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/TemplateWriter.js:331:3)
[11ty]     at async TemplateWriter.generateTemplates (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/TemplateWriter.js:361:3)
[11ty] Copied 161 files / Wrote 0 files in 3.13 seconds (v3.0.0-alpha.5)
[11ty] Eleventy CLI Error: (more in DEBUG output)
[11ty] 1. Having trouble rendering liquid template ./src/content/language/macros.md (via TemplateContentRenderError)
[11ty] 2. Cannot read properties of null (reading 'length') (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of null (reading 'length')
[11ty]     at markdown.renderer.rules.fence (file:///Users/mbelanger/Projects/dart.dev/dart-3/src/_11ty/plugins/highlight.js:49:37)
[11ty]     at Renderer.render (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/markdown-it@14.1.0/node_modules/markdown-it/lib/renderer.mjs:313:28)
[11ty]     at MarkdownIt.render (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/markdown-it@14.1.0/node_modules/markdown-it/lib/index.mjs:530:24)
[11ty]     at file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/Engines/Markdown.js:79:33
[11ty]     at async Template._render (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/TemplateContent.js:532:19)
[11ty]     at async Template.renderPageEntryWithoutLayout (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/Template.js:432:25)
[11ty]     at async TemplateMap.populateContentDataInMap (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/TemplateMap.js:545:7)
[11ty]     at async TemplateMap.cache (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/TemplateMap.js:473:3)
[11ty]     at async TemplateWriter._createTemplateMap (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/TemplateWriter.js:331:3)
[11ty]     at async TemplateWriter.generateTemplates (file:///Users/mbelanger/Projects/dart.dev/dart-3/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.5/node_modules/@11ty/eleventy/src/TemplateWriter.js:361:3)
```

### Expected fix

halp

### On which platform(s) did you experience this issue?

macOS

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/commit/926f56c63be2a6a54ef6c1f2c30a38ca5bfb61a8
